version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: smartsecurec3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - smartsecure_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - smartsecure_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/smartsecurec3
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - smartsecure_network

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - smartsecure_network

  ai_worker:
    build: ./backend
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/smartsecurec3
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - smartsecure_network

volumes:
  postgres_data:
  node_modules:

networks:
  smartsecure_network:
    driver: bridge